services:
  api-gateway:
    build:
      context: ./services/api-gateway
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    environment:
      - PORT=${API_GATEWAY_PORT}
      - PRESCRIPTION_SERVICE_URL=http://prescription-service:${PRESCRIPTION_PORT}
    depends_on:
      - prescription-service
    networks:
      - app-network
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  prescription-service:
    build:
      context: ./services/prescription-service
    ports:
      - ${PRESCRIPTION_PORT}:${PRESCRIPTION_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    networks:
      - app-network
    volumes:
      - ./services/prescription-service:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

networks:
  app-network:
    driver: bridge

volumes:
  prescription-db-data:
