services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PRESCRIPTION_SERVICE_URL=http://prescription-service:3001
    depends_on:
      - prescription-service
    networks:
      - app-network
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules

  prescription-service:
    build:
      context: ./prescription-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - app-network
    volumes:
      - ./prescription-service:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge
